version: "3.8"

services:
  apigateway:
    build: ./ApiGateway
    ports:
      - "7076:8080"
    container_name: apigateway
    restart: always
    environment:
      - ReverseProxy__Clusters__brandCluster__Destinations__brandService__Address=http://brand-service:8080/
      - ReverseProxy__Clusters__dealerCluster__Destinations__dealerService__Address=http://dealer-service:8080/

  dealer-service:
    build: ./DealerService
    ports:
      - "7259:8080"
    container_name: dealer-service
    restart: always
    env_file:
      - ./DealerService/.env

  brand-service:
    build: ./BrandService
    ports:
      - "7195:8080"
    container_name: brand-service
    restart: always
    env_file:
      - ./BrandService/.env

  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    depends_on:
      - apigateway

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "sleep 5 && certbot certonly --webroot --webroot-path=/var/www/certbot --email lehuyvuok@gmail.com --agree-tos --no-eff-email -d evm.webredirect.org"

networks:
  default:
    driver: bridge

