version: '3.8'

services:
  apigateway:
    build: ./ApiGateway
    ports:
      - "7076:8080"
    container_name: apigateway
    restart: always
    environment:
      - ReverseProxy__Clusters__brandCluster__Destinations__brandService__Address=https://brandservice:8080/
      - ReverseProxy__Clusters__dealerCluster__Destinations__dealerService__Address=https://dealerservice:8080/

  dealer-service:
    build: ./DealerService
    ports:
      - "7259:8080"
    container_name: dealer-service
    restart: always
    env_file:
      - ./DealerService/.env
        

  brand-service:
    build: ./BrandService
    ports:
      - "7195:8080"
    container_name: brand-service
    restart: always
    env_file:
      - ./BrandService/.env
