version: "3.8"

services:
  apigateway:
    build: ./ApiGateway
    ports:
      - "7076:8080"
    container_name: apigateway
    restart: always
    environment:
      - ReverseProxy__Clusters__brandCluster__Destinations__brandService__Address=http://brand-service:8080/
      - ReverseProxy__Clusters__dealerCluster__Destinations__dealerService__Address=http://dealer-service:8080/
      - ReverseProxy__Clusters__financialCluster__Destinations__financialService__Address=http://financial-service:8080/
      - ReverseProxy__Clusters__identityCluster__Destinations__identityService__Address=http://identity-service:8080/
      - ReverseProxy__Clusters__utilityCluster__Destinations__utilityService__Address=http://utility-service:8080/

  dealer-service:
    build: ./DealerService
    ports:
      - "7259:8080"
    container_name: dealer-service
    restart: always
    env_file:
      - ./DealerService/.env

  brand-service:
    build: ./BrandService
    ports:
      - "7195:8080"
    container_name: brand-service
    restart: always
    env_file:
      - ./BrandService/.env

  financial-service:
    build: ./FinancialService
    ports:
      - "7090:8080"
    container_name: financial-service
    restart: always
    env_file:
      - ./FinancialService/.env

  identity-service:
    build: ./IdentityService
    ports:
      - "7070:8080"
    container_name: identity-service
    restart: always
    env_file:
      - ./IdentityService/.env

  utility-service:
    build: ./UtilityService
    ports:
      - "7050:8080"
    container_name: utility-service
    restart: always
    env_file:
      - ./UtilityService/.env
  
  customer-service:
    build: ./CustomerService
    ports:
      - "1223:8080"
    container_name: customer-service
    restart: always
    env_file:
      - ./CustomerService/.env

networks:
  default:
    driver: bridge
